### ISSUE TITLE
FINISH

### ISSUE THREAD

**Issue by meishimomura** [team-kamibukuro/hacku2022-front#44]
## Tasks

- [x] 時間を保持
- [x] テストケースがすべて通った\*1
- [x] event": "FINISHED"を受け取ったらそのユーザーがFINISHEDと表示する
- [x] current user の保持している時間と playerid, name をなげる\*2
  - [x] + 制限時間が終了したときにもなげる
- [x] event: RANKING を受け取ったらFINISH画面を表示する\*3

## 概要

テストケース実行

↓

フロント：
テストケース実行 API のテストケースがすべて OK だったら、

- 時間を保持

- テストケースがすべて通った websocket をなげる\*1

↓

バック：

ブロードキャスト\*1

...全員が終了した場合 次へ

バック：

- 全員が終了した通知 websocket をなげる\*2

  ↓

フロント：

- current user の保持している時間と playerid, name をなげる\*2

↓

バック：

- 受け取った時間を集計してフロントにブロードキャスト\*3

#### テストケースがすべて通った \*1

* フロント->バック
```  JSON
{
  "event": "FINISHED",
  "playerId": "",
  "name": ""
}
```
* バック->フロント
```  JSON
{
  "event": "FINISHED",
  "playerId": "",
  "name": ""
}
```

#### 全員が終了した \*2

* バック->フロント
``` JSON
{
  "event": "ALL_FINISHED",
}
```

* フロント->バック
``` JSON
{
  "event": "ALL_FINISHED",
  "playerId": "",
  "name": "",
  "time": "", 差分
}
```

#### 集計 \*3

* バック->フロント
```JSON
{
  "event": "RANKING",
  "users": [{
      "playerId": "",
      "name": "",
      "time": "",
      "rank": 1,
    },
    {
      "playerId": "",
      "name": "",
      "time": "",
      "rank": 1,
    }]
}
```
